name: C++ CI

on:
  pull_request

jobs:
  test:
    name: Tests in ${{ matrix.build_type }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Release, Debug, RelWithDebInfo]

    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install binutils g++-10 cmake valgrind python3 python3-pip && sudo pip install colorama termcolor
      - name: Create fixes dir
        run: mkdir .fixes-internal
      - name: Checkout fixes repository
        uses: actions/checkout@v2
        with:
          repository: 'ITMO-CPP-IB/fixes'
          path: '.fixes-internal/fixes'
      - name: Apply fixes
        run: python3 apply-fixes.py --on-github

      - name: Build main
        run: CXX=g++-10 bash scripts/build.sh ${{ matrix.build_type }}

      - name: Test main
        run: python3 run-tests.py -t public -c ${{ matrix.build_type }}
